apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-app
  labels:
    app: api
spec:
    replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - image: zhenweiwong/drf-api-practice:latest
          name: api

          ports:
            - containerPort: 3013
              name: gunicorn