apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
  - host: apiapp.kube.com
    http:
      paths:
      - backend:
          serviceName: api-app-service
          servicePort: 3013