# Generated by Django 3.1.2 on 2020-11-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='book',
            field=models.ManyToManyField(blank=True, null=True, related_name='authors', to='api.Book'),
        ),
    ]
