# Generated by Django 3.1.2 on 2020-11-08 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201105_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknumber',
            name='isbn10',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='booknumber',
            name='isbn13',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(13)]),
        ),
    ]
